### PR TITLE
[dev]Horizontal Barchart added

### LINKED ISSUE #76: [New Work] Add new chart types in the chart selector
**What is the work should be done please be clear and short about the work**
add as many types of chart as you can in the chart selector be it doughnat pie differnet type of line chart what else be creative thats all.

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Check the src/components folder and you will understand 

**The Best way to implement this (if any) **
be creative we always welcome creative contributors 

**Additional context** 
NA

### PR DESCRIPTION
**Pull request by Thilagavathi1**
# Description

Add PolaHorizontal BarChart to the list of charts.
Fixes #76

## Type of change

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] This PR is made on develop branch
- [ ] I have mentioned above the issue number which i have solved
- [ ] I have not changed anything in the files .all-contributorsrc and The Contributor section in Readme.md
- [ ] My code follows the proper indentation style of the project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@Thilagavathi1 your code is not built properly chek the cheks in the PR all have been cross marked please fi them otherwise I will labl the PR  as invalid

**Comment by Thilagavathi1** [comment]
ok let me resolve this

**Comment by ayan-biswas0412** [comment]
> ok let me resolve this

yeah

**Comment by Thilagavathi1** [comment]
check has been passed is it fine now? @ayan-biswas0412

**Comment by Thilagavathi1** [comment]
@ayan-biswas0412 Do u have an_updated in this PR_

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @Thilagavathi1 for code

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @Thilagavathi1 for code

**Pull request merged**
