### PR TITLE
Code editor added

### PR DESCRIPTION
**Pull request by ankit-rawani**
# Description
- Code editor implemented using code mirror
- X-overflow of the webpage fixed

## Dependencies
- codemirror
- react-codemirror2

## Type of change
New feature added, one small bug fixed

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] I have installed additional dependency

# Checklist:

- [x] This PR is made on develop branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

#33

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image
Maintain a minimum gap from the footer component otherwise it looks good
Also add a run button (just button which is clickable but doesnt has any action) @ankit-rawani

**Comment by ankit-rawani** [comment]
Okay

**Comment by ayan-biswas0412** [comment]
@ankit-rawani yah nice but add a run button in the header of the code editor

**Comment by ankit-rawani** [comment]
Is there any functionality to be given to the button, or just a dummy button?

**Comment by ankit-rawani** [comment]
@ayan-biswas0412 Review the changes please

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @ankit-rawani for code

**Pull request merged**
