### PR TITLE
logo updated

### PR DESCRIPTION
**Pull request by pearlpandz**
SVG Logo File updated

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
make your PR to the develop branch not in the master

**Review by ayan-biswas0412 — COMMENTED** [review]
and also give a png file

**Comment by pearlpandz** [comment]
> and also give a png file

Sure

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @pearlpandz  for design

**Comment by ayan-biswas0412** [comment]
@pearlpandz fix the things and maintain the contributor's guide change your PR according to that .
Tasks to be done
1. Add png file
2. Make PR to develop branch
3. Resolve the conflicts
I have included you as collaborator as i have used your logo in the organization you can check the readme file.
do the tasks and after that i will give you the hacktoberfest-accepted label

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
your branch is not updated with develop branch aso conflicts are not resolved

**Comment by pearlpandz** [comment]
> your branch is not updated with develop branch also conflicts are not resolved

Please check now, my develop branch code updated

**Comment by ayan-biswas0412** [comment]
your contribution is accepted and i am closing this

**Pull request closed without merging**
