### PR TITLE
Added code of conduct page

### PR DESCRIPTION
**Pull request by dudakp**
# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] I have installed additional dependency

# Checklist:

- [ ] This PR is made on develop branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image

Your work is not deployable and it was not deployed correctly please see the screenshot and make sure that it is discoverable then i can approve this

**Comment by dudakp** [comment]
Hello, I can't identify error based on screenshot you send, but I resolver one merge pending conflict, pleasy try to deployt it again and let me know the result. Cheers

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image
Make the thing more eye appealing it seems there is no difference in the styling , alignment of the markdown file and the react page

**Comment by dudakp** [comment]
I made small changes in styling. If you have any other ideas let me know. I think that CoC page could be clean and simple.

**Comment by ayan-biswas0412** [comment]
@dudakp but still it is not coming in deployment are you working in that problem ?? please let me know otherwise I will close this PR

**Pull request closed without merging**
