### PR TITLE
Adds Contributor Page

### LINKED ISSUE #115: [New Work] Make a contributor page by parsing the Readme file
**What is the work should be done please be clear and short about the work**
All the contributos are given in the Readme file now you have to make a react page by parsing the data and generate it dynamically such that any change in Readme shoud also reflect in the React page .
There should be a button " Contributors" in the navbar and the footer => onclick => should redirect to the page

**What the work is all about? Is there any specific files that need to be changed please include those.**
Be creative and make the best possible thing

**The Best way to implement this (if any) **
NA
**Additional context** 
NA

### PR DESCRIPTION
**Pull request by jmannfeld**
# Description

To create a custom contributors page within the app, I added a markdown file to the `files` attribute in `.all-contributorsrc`. When [all-contributors generate](https://allcontributors.org/docs/en/cli/usage#all-contributors-generate) is run, this will also update the new markdown file within the full list of current contributors.

To import the markdown file with the .jsx, I installed a good package for doing this: [react-markdown](https://github.com/remarkjs/react-markdown).

Please let me know if you have any questions!

Fixes #115 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] I have installed additional dependency

# Checklist:

- [x] This PR is made on develop branch
- [x] I have mentioned above the issue number which i have solved
- [ ] I have not changed anything in the files .all-contributorsrc and The Contributor section in Readme.md
- [x] My code follows the proper indentation style of the project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
@jmannfeld your page is not visible after deployment

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
@jmannfeld you page is not viisble after deployment check the netlify deployment status

**Comment by jmannfeld** [comment]
@ayan-biswas0412 Hmm okay, I will take a look at that

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 Hmm okay, I will take a look at that

thanks

**Comment by jmannfeld** [comment]
Hi, I have updated the links in the Navbar and Footer to now use react-router Link. I believe that was the issue before. I am now seeing the page load in the preview deploy 😄

**Pull request closed without merging**
