### PR TITLE
[dev] Added panel that shows mathematical expressions

### LINKED ISSUE #62: [New Work] Make a panel in which simple mathematical equation can be written
**What is the work should be done please be clear and short about the work**
Be creative and make a panel in which simple mathematical functions can be written and render the component in HomePage.js

**What the work is all about? Is there any specific files that need to be changed please include those.**
Just the panel should take input simple mathemital functions (simple integration , derivative )

**The Best way to implement this (if any) **
Be creative there is no strict way to do it

**Additional context** 
NA

### PR DESCRIPTION
**Pull request by theamritanair**
# Description
I've added a panel in the Homepage called Equation, where a textbox is provided. On entering expressions, it displays them in Latex format.
Used the MathJax package for React by [Wing-Hong Andrew Ko](https://github.com/wko27)
image

Fixes #62  

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update
- [x] I have installed additional dependency

# Checklist:

- [x] This PR is made on develop branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image
Make a plot button (just a button which is clickable but does noting at the side of the equation text ) and make the height of the panel like the code editor and make sure that it supports multi line currently it supports only single line

**Comment by theamritanair** [comment]
@ayan-biswas0412 by "make the height of the panel like the code editor" you mean the input panel right?

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image
It is giving math processing error  fix it and rest is fine

**Comment by theamritanair** [comment]
It doesn't show me that error. When does it show the error for you?

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @theamritanair for code

**Comment by ayan-biswas0412** [comment]
@theamritanair nice work

**Pull request merged**
