### PR TITLE
tittle and mobile view issues corrected

### PR DESCRIPTION
**Pull request by Sooraj-s-98**
# Description

Please include a summary of the change and which issue is fixed.
Please also include relevant motivation and context.
List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] I have installed additional dependency

# Checklist:

- [x] This PR is made on develop branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Sooraj-s-98** [comment]
corrected mobile view.
mobile view

**Comment by ayan-biswas0412** [comment]
@Sooraj-s-98 your deploy preview is failed please fix that

**Comment by ayan-biswas0412** [comment]
Your deploy preview is still not ok and this issue is resolved and another participant has resolved this already so i am closing this please see for other issues there are some new also

**Comment by Sooraj-s-98** [comment]
what invalided @ayan-biswas0412 
can you remove invalid label

**Comment by ayan-biswas0412** [comment]
> what invalided @ayan-biswas0412
> can you remove invalid label

your deploy preview is failed constantly

**Pull request closed without merging**
