### PR TITLE
[dev] Add Polar Chart

### LINKED ISSUE #76: [New Work] Add new chart types in the chart selector
**What is the work should be done please be clear and short about the work**
add as many types of chart as you can in the chart selector be it doughnat pie differnet type of line chart what else be creative thats all.

**What the work is all about ? Is there any specific files that need to be changed please include those.**
Check the src/components folder and you will understand 

**The Best way to implement this (if any) **
be creative we always welcome creative contributors 

**Additional context** 
NA

### PR DESCRIPTION
**Pull request by rdhaundiyal-indeed**
# Description

Add Polar Chart to the list of charts.

Fixes #76 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] This PR is made on develop branch
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
Add some more types (at least 2 more types)

**Comment by rdhaundiyal-indeed** [comment]
Sure. Is it a good idea to add them in separate PRs? Please let me know. Thanks.

**Comment by ayan-biswas0412** [comment]
> Sure. Is it a good idea to add them in separate PRs? Please let me know. Thanks.

no don't do separate PR please add your changes here

**Comment by ayan-biswas0412** [comment]
Good work @rdhaundiyal-indeed

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @rdhaundiyal-indeed for code

**Pull request merged**
