### PR TITLE
Implement the Footer Component for the Homepage

### PR DESCRIPTION
**Pull request by femakin**

### CODE REVIEW

**Comment by ayan-biswas0412** [comment]
Chane branch to develop and resolve the conflicts

**Comment by femakin** [comment]
Conflicts resolved, please check

**Review by ayan-biswas0412 — CHANGES_REQUESTED** [review]
image
The footer should be a component and should be in src/components not inside the homepage foler and also please give some icons in the footer and change the lorel ipsums to some proper value and attach the logo in the footer

**Comment by femakin** [comment]
Alright, I will work on the changes but where do I get the logo

**Comment by ayan-biswas0412** [comment]
> Alright, I will work on the changes but where do I get the logo

check src/assets/logo.png

**Comment by ayan-biswas0412** [comment]
@all-contributors please add @femakin for code

Goow work @femakin

**Comment by ayan-biswas0412** [comment]
good work @femakin

**Comment by femakin** [comment]
Thank You @ayan-biswas0412

**Pull request merged**
